//! Parameter contract shared by the native plugin and frontend code generation.
//!
//! This crate intentionally stays independent of `wrac_clap_adapter`: the plugin maps
//! this product-level contract into host-specific `ParamInfo`, while build.rs maps the
//! same contract into checked-in TypeScript constants for the WebView GUI.

use std::collections::BTreeSet;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ParameterKind {
    Bypass,
    Gain,
}

/// Product-domain metadata for one stable host parameter.
///
/// IDs and plain ranges live here so host automation, DSP values, and generated GUI
/// constants cannot drift. Parameter-specific parsing and DSP behavior still live in
/// the plugin crate because those are executable behavior, not static contract data.
#[derive(Debug, Clone, Copy)]
pub struct ParameterContract {
    pub key: &'static str,
    pub id_const: &'static str,
    pub id: u32,
    pub name: &'static str,
    pub kind: ParameterKind,
    pub host_min: f64,
    pub host_max: f64,
    pub host_default: f64,
    pub plain_min: f64,
    pub plain_max: f64,
    pub plain_default: f64,
    pub automatable: bool,
    pub stepped: bool,
    pub is_enum: bool,
    pub is_bypass: bool,
    pub gui_role: Option<&'static str>,
}

// Parameter IDs are host/project ABI. Never renumber an existing id after publishing;
// add new ids instead so saved automation keeps targeting the same control.
pub const PARAM_BYPASS_ID: u32 = 0;
pub const PARAM_GAIN_ID: u32 = 1;

// Gain is a linear amplitude. 1.0 = 0 dB (unity), 0.0 = silence, 2.0 = +6 dB.
pub const MIN_GAIN: f32 = 0.0;
pub const MAX_GAIN: f32 = 2.0;
pub const DEFAULT_GAIN: f32 = 1.0;

pub const PARAMETER_SPECS: &[ParameterContract] = &[
    ParameterContract {
        key: "bypass",
        id_const: "PARAM_BYPASS_ID",
        id: PARAM_BYPASS_ID,
        name: "Bypass",
        kind: ParameterKind::Bypass,
        host_min: 0.0,
        host_max: 1.0,
        host_default: 0.0,
        plain_min: 0.0,
        plain_max: 1.0,
        plain_default: 0.0,
        // Keep bypass host-visible and enum-shaped so wrappers/hosts can expose native
        // bypass controls instead of treating it as an ordinary continuous parameter.
        automatable: true,
        stepped: true,
        is_enum: true,
        is_bypass: true,
        gui_role: None,
    },
    ParameterContract {
        key: "gain",
        id_const: "PARAM_GAIN_ID",
        id: PARAM_GAIN_ID,
        name: "Gain",
        kind: ParameterKind::Gain,
        host_min: 0.0,
        host_max: 1.0,
        host_default: ((DEFAULT_GAIN - MIN_GAIN) / (MAX_GAIN - MIN_GAIN)) as f64,
        plain_min: MIN_GAIN as f64,
        plain_max: MAX_GAIN as f64,
        plain_default: DEFAULT_GAIN as f64,
        // Gain is the template's primary editable control, so it remains automatable
        // even though the GUI is a simple one-knob surface.
        automatable: true,
        stepped: false,
        is_enum: false,
        is_bypass: false,
        gui_role: Some("gain"),
    },
];

pub fn render_typescript_parameter_contract() -> String {
    let roles = PARAMETER_SPECS
        .iter()
        .filter_map(|spec| spec.gui_role)
        .collect::<BTreeSet<_>>();
    let role_union = if roles.is_empty() {
        "never".to_string()
    } else {
        roles
            .iter()
            .map(|role| json_string_literal(role))
            .collect::<Vec<_>>()
            .join(" | ")
    };

    let mut ts = String::from(
        "// Generated by src-plugin/build.rs from parameter-contract/src/lib.rs. Do not edit by hand.\n",
    );
    ts.push_str(
        "// Parameter ids are host/project ABI; renumbering them breaks saved automation.\n\n",
    );
    ts.push_str(&format!("export type GuiParameterRole = {role_union};\n\n"));
    ts.push_str("export type ParameterSpec = {\n");
    ts.push_str("  readonly id: number;\n");
    ts.push_str("  readonly name: string;\n");
    ts.push_str("  readonly minValue: number;\n");
    ts.push_str("  readonly maxValue: number;\n");
    ts.push_str("  readonly defaultValue: number;\n");
    ts.push_str("  readonly guiRole: GuiParameterRole | null;\n");
    ts.push_str("};\n\n");

    for spec in PARAMETER_SPECS {
        ts.push_str(&format!("export const {} = {};\n", spec.id_const, spec.id));
    }
    ts.push('\n');

    ts.push_str("export const PARAMETERS = {\n");
    for spec in PARAMETER_SPECS {
        let gui_role = spec
            .gui_role
            .map(json_string_literal)
            .unwrap_or_else(|| "null".to_string());
        ts.push_str(&format!("  {}: {{\n", spec.key));
        ts.push_str(&format!("    id: {},\n", spec.id_const));
        ts.push_str(&format!("    name: {},\n", json_string_literal(spec.name)));
        ts.push_str(&format!(
            "    minValue: {},\n",
            number_literal(spec.plain_min)
        ));
        ts.push_str(&format!(
            "    maxValue: {},\n",
            number_literal(spec.plain_max)
        ));
        ts.push_str(&format!(
            "    defaultValue: {},\n",
            number_literal(spec.plain_default)
        ));
        ts.push_str(&format!("    guiRole: {gui_role},\n"));
        ts.push_str("  },\n");
    }
    ts.push_str("} as const satisfies Record<string, ParameterSpec>;\n\n");

    let gui_keys = PARAMETER_SPECS
        .iter()
        .filter(|spec| spec.gui_role.is_some())
        .map(|spec| format!("PARAMETERS.{}", spec.key))
        .collect::<Vec<_>>();
    ts.push_str(&format!(
        "export const GUI_PARAMETERS = [{}] as const;\n",
        gui_keys.join(", ")
    ));
    for spec in PARAMETER_SPECS
        .iter()
        .filter(|spec| spec.gui_role.is_some())
    {
        ts.push_str(&format!(
            "export const {}_PARAMETER = PARAMETERS.{};\n",
            screaming_snake(spec.key),
            spec.key
        ));
    }

    ts
}

fn number_literal(value: f64) -> String {
    if value == 0.0 {
        return "0".to_string();
    }
    let literal = value.to_string();
    if literal.contains('.') {
        literal
    } else {
        format!("{literal}.0")
    }
}

fn screaming_snake(value: &str) -> String {
    let mut output = String::new();
    for (index, character) in value.chars().enumerate() {
        if character.is_ascii_alphanumeric() {
            if index > 0 && character.is_ascii_uppercase() {
                output.push('_');
            }
            output.push(character.to_ascii_uppercase());
        } else if !output.ends_with('_') {
            output.push('_');
        }
    }
    output.trim_matches('_').to_string()
}

fn json_string_literal(value: &str) -> String {
    let mut output = String::from("\"");
    for character in value.chars() {
        match character {
            '"' => output.push_str("\\\""),
            '\\' => output.push_str("\\\\"),
            '\n' => output.push_str("\\n"),
            '\r' => output.push_str("\\r"),
            '\t' => output.push_str("\\t"),
            character if character.is_control() => {
                output.push_str(&format!("\\u{:04x}", character as u32));
            }
            character => output.push(character),
        }
    }
    output.push('"');
    output
}
