//! Build script that bundles `src-gui/dist` into a single zip and writes it to `OUT_DIR`
//! for release builds.
//!
//! The resulting zip is embedded into the plugin binary via `include_bytes!` in `gui.rs`
//! and served at runtime by the WebView under the `wxp-plugin://` scheme.
//! In debug builds Vite's dev server is used instead, so this script does nothing.

use std::collections::HashSet;
use std::env;
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::{Path, PathBuf};

use serde::Deserialize;
use zip::CompressionMethod;
use zip::ZipWriter;
use zip::write::SimpleFileOptions;

fn main() {
    // Tell Cargo to rebuild (regenerate the zip) whenever frontend source files change.
    println!("cargo:rerun-if-changed=../src-gui/index.html");
    println!("cargo:rerun-if-changed=../src-gui/src");
    println!("cargo:rerun-if-changed=../src-gui/package.json");
    println!("cargo:rerun-if-changed=../src-gui/vite.config.ts");
    println!("cargo:rerun-if-changed=Cargo.toml");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let manifest_path = manifest_dir.join("Cargo.toml");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    // Make [package.metadata.wrac] in Cargo.toml the single source of truth for plugin
    // identity. The plugin descriptor table is generated from it below, while xtask reads
    // the same manifest directly for wrapper and artifact names.
    let metadata = read_wrac_metadata(&manifest_path).expect("failed to read WRAC metadata");
    write_plugin_products(&metadata, &out_dir)
        .expect("failed to write WRAC plugin product metadata");
    // Skip zip creation for debug builds (the Vite dev server is used instead).
    if env::var("PROFILE").ok().as_deref() != Some("release") {
        return;
    }

    let gui_dist_dir = manifest_dir
        .parent()
        .expect("src-plugin must have a parent directory")
        .join("src-gui")
        .join("dist");
    let out_zip =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("wrac_gain_plugin_gui.zip");

    // Fail early if `npm run build` was not run before the release build.
    if !gui_dist_dir.exists() {
        panic!(
            "frontend build output was not found at {}. Run `npm install && npm run build` in src-gui before release builds.",
            gui_dist_dir.display()
        );
    }

    create_zip(&gui_dist_dir, &out_zip).expect("failed to create frontend zip");
}

fn write_plugin_products(metadata: &WracMetadata, out_dir: &Path) -> io::Result<()> {
    // Rust cannot iterate over Cargo manifest metadata at compile time. Generate the
    // descriptor table once in build.rs so the plugin factory still has a static,
    // allocation-free source for count/descriptor/create queries.
    let mut rust =
        String::from("// Generated by build.rs from package.metadata.wrac. Do not edit by hand.\n");
    rust.push_str(&format!(
        "pub(crate) const COMPANY_NAME: &str = {:?};\n",
        metadata.company_name
    ));
    rust.push_str(&format!(
        "pub(crate) const AUV2_MANUFACTURER_CODE: [u8; 4] = {};\n",
        four_ascii_array_literal(&metadata.auv2_manufacturer_code)
    ));
    // CLAP hosts read feature strings during discovery. Generate them from the
    // manifest so the production-readiness checks and runtime descriptor cannot
    // drift after a product rename or capability change.
    for (index, plugin) in metadata.plugins.iter().enumerate() {
        rust.push_str(&format!(
            "const PLUGIN_{index}_FEATURES: &[PluginFeature] = &{};\n",
            plugin_feature_array_literal(&plugin.clap_features)?
        ));
    }
    rust.push_str("pub(crate) const PLUGIN_DESCRIPTORS: &[PluginDescriptor] = &[\n");
    for (index, plugin) in metadata.plugins.iter().enumerate() {
        rust.push_str("    PluginDescriptor {\n");
        rust.push_str(&format!("        id: {:?},\n", plugin.plugin_id));
        rust.push_str(&format!("        name: {:?},\n", plugin.plugin_name));
        rust.push_str("        vendor: COMPANY_NAME,\n");
        rust.push_str(&format!("        url: {:?},\n", metadata.homepage_url));
        rust.push_str(&format!("        manual_url: {:?},\n", metadata.manual_url));
        rust.push_str(&format!(
            "        support_url: {:?},\n",
            metadata.support_url
        ));
        rust.push_str("        version: env!(\"CARGO_PKG_VERSION\"),\n");
        rust.push_str(&format!(
            "        description: {:?},\n",
            metadata.description
        ));
        rust.push_str(&format!("        features: PLUGIN_{index}_FEATURES,\n"));
        rust.push_str("        auv2: Some(Auv2Descriptor {\n");
        rust.push_str("            manufacturer_code: AUV2_MANUFACTURER_CODE,\n");
        rust.push_str("            manufacturer_name: COMPANY_NAME,\n");
        rust.push_str(&format!(
            "            plugin_type: {},\n",
            four_ascii_array_literal(&plugin.auv2_type)
        ));
        rust.push_str(&format!(
            "            plugin_subtype: {},\n",
            four_ascii_array_literal(&plugin.auv2_subtype)
        ));
        rust.push_str("        }),\n");
        rust.push_str("    },\n");
    }
    rust.push_str("];\n");
    fs::write(out_dir.join("wrac_plugin_products.rs"), rust)
}

fn four_ascii_array_literal(value: &str) -> String {
    let bytes = value.as_bytes();
    format!("[{}, {}, {}, {}]", bytes[0], bytes[1], bytes[2], bytes[3])
}

fn plugin_feature_array_literal(features: &[String]) -> io::Result<String> {
    let mut items = Vec::new();
    for feature in features {
        items.push(plugin_feature_literal(feature)?);
    }
    Ok(format!("[{}]", items.join(", ")))
}

fn plugin_feature_literal(feature: &str) -> io::Result<&'static str> {
    match feature {
        "audio-effect" => Ok("PluginFeature::AudioEffect"),
        "analyzer" => Ok("PluginFeature::Analyzer"),
        "ambisonic" => Ok("PluginFeature::Ambisonic"),
        "chorus" => Ok("PluginFeature::Chorus"),
        "compressor" => Ok("PluginFeature::Compressor"),
        "de-esser" => Ok("PluginFeature::DeEsser"),
        "delay" => Ok("PluginFeature::Delay"),
        "instrument" => Ok("PluginFeature::Instrument"),
        "note-effect" => Ok("PluginFeature::NoteEffect"),
        "note-detector" => Ok("PluginFeature::NoteDetector"),
        "drum" => Ok("PluginFeature::Drum"),
        "drum-machine" => Ok("PluginFeature::DrumMachine"),
        "equalizer" => Ok("PluginFeature::Equalizer"),
        "expander" => Ok("PluginFeature::Expander"),
        "filter" => Ok("PluginFeature::Filter"),
        "flanger" => Ok("PluginFeature::Flanger"),
        "frequency-shifter" => Ok("PluginFeature::FrequencyShifter"),
        "gate" => Ok("PluginFeature::Gate"),
        "glitch" => Ok("PluginFeature::Glitch"),
        "granular" => Ok("PluginFeature::Granular"),
        "distortion" => Ok("PluginFeature::Distortion"),
        "limiter" => Ok("PluginFeature::Limiter"),
        "mastering" => Ok("PluginFeature::Mastering"),
        "mixing" => Ok("PluginFeature::Mixing"),
        "mono" => Ok("PluginFeature::Mono"),
        "multi-effects" => Ok("PluginFeature::MultiEffects"),
        "phaser" => Ok("PluginFeature::Phaser"),
        "phase-vocoder" => Ok("PluginFeature::PhaseVocoder"),
        "pitch-correction" => Ok("PluginFeature::PitchCorrection"),
        "pitch-shifter" => Ok("PluginFeature::PitchShifter"),
        "restoration" => Ok("PluginFeature::Restoration"),
        "reverb" => Ok("PluginFeature::Reverb"),
        "sampler" => Ok("PluginFeature::Sampler"),
        "stereo" => Ok("PluginFeature::Stereo"),
        "surround" => Ok("PluginFeature::Surround"),
        "synthesizer" => Ok("PluginFeature::Synthesizer"),
        "transient-shaper" => Ok("PluginFeature::TransientShaper"),
        "tremolo" => Ok("PluginFeature::Tremolo"),
        "utility" => Ok("PluginFeature::Utility"),
        _ => Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("unsupported package.metadata.wrac.plugins.clap_features value: {feature}"),
        )),
    }
}

#[derive(Debug, Deserialize)]
struct CargoManifest {
    package: CargoPackage,
}

#[derive(Debug, Deserialize)]
struct CargoPackage {
    metadata: Option<PackageMetadata>,
}

#[derive(Debug, Deserialize)]
struct PackageMetadata {
    wrac: Option<WracMetadata>,
}

#[derive(Debug, Deserialize)]
struct WracMetadata {
    company_name: String,
    auv2_manufacturer_code: String,
    bundle_identifier: String,
    homepage_url: String,
    manual_url: String,
    support_url: String,
    description: String,
    copyright: String,
    plugins: Vec<WracPluginMetadata>,
}

#[derive(Debug, Deserialize)]
struct WracPluginMetadata {
    plugin_id: String,
    plugin_name: String,
    clap_features: Vec<String>,
    standalone_name: String,
    auv2_type: String,
    auv2_subtype: String,
}

fn read_wrac_metadata(manifest_path: &Path) -> io::Result<WracMetadata> {
    let manifest = fs::read_to_string(manifest_path)?;
    let cargo_manifest: CargoManifest = toml::from_str(&manifest)
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?;
    let metadata = cargo_manifest
        .package
        .metadata
        .ok_or_else(missing_wrac_metadata)?
        .wrac
        .ok_or_else(missing_wrac_metadata)?;
    validate_required("package.metadata.wrac.company_name", &metadata.company_name)?;
    validate_four_ascii("auv2_manufacturer_code", &metadata.auv2_manufacturer_code)?;
    validate_required(
        "package.metadata.wrac.bundle_identifier",
        &metadata.bundle_identifier,
    )?;
    validate_required("package.metadata.wrac.homepage_url", &metadata.homepage_url)?;
    validate_required("package.metadata.wrac.manual_url", &metadata.manual_url)?;
    validate_required("package.metadata.wrac.support_url", &metadata.support_url)?;
    validate_required("package.metadata.wrac.description", &metadata.description)?;
    validate_required("package.metadata.wrac.copyright", &metadata.copyright)?;
    if metadata.plugins.is_empty() {
        return Err(missing_metadata("plugins"));
    }
    let mut plugin_ids = HashSet::new();
    let mut standalone_names = HashSet::new();
    let mut auv2_ids = HashSet::new();
    for plugin in &metadata.plugins {
        validate_required("package.metadata.wrac.plugins.plugin_id", &plugin.plugin_id)?;
        validate_required(
            "package.metadata.wrac.plugins.plugin_name",
            &plugin.plugin_name,
        )?;
        validate_non_empty_list(
            "package.metadata.wrac.plugins.clap_features",
            &plugin.clap_features,
        )?;
        for feature in &plugin.clap_features {
            plugin_feature_literal(feature)?;
        }
        validate_required(
            "package.metadata.wrac.plugins.standalone_name",
            &plugin.standalone_name,
        )?;
        validate_four_ascii("auv2_type", &plugin.auv2_type)?;
        validate_four_ascii("auv2_subtype", &plugin.auv2_subtype)?;
        validate_unique("plugin_id", &plugin.plugin_id, &mut plugin_ids)?;
        validate_unique(
            "standalone_name",
            &plugin.standalone_name,
            &mut standalone_names,
        )?;
        if !auv2_ids.insert((plugin.auv2_type.as_str(), plugin.auv2_subtype.as_str())) {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "package.metadata.wrac.plugins AUv2 type/subtype must be unique: {}/{}",
                    plugin.auv2_type, plugin.auv2_subtype
                ),
            ));
        }
    }
    Ok(metadata)
}

fn validate_non_empty_list(key: &str, values: &[String]) -> io::Result<()> {
    if values.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{key} must not be empty"),
        ));
    }
    for value in values {
        validate_required(key, value)?;
    }
    Ok(())
}

fn missing_metadata(key: &str) -> io::Error {
    io::Error::new(
        io::ErrorKind::InvalidData,
        format!("missing package.metadata.wrac.{key} in src-plugin/Cargo.toml"),
    )
}

fn missing_wrac_metadata() -> io::Error {
    io::Error::new(
        io::ErrorKind::InvalidData,
        "missing package.metadata.wrac in src-plugin/Cargo.toml",
    )
}

fn validate_required(key: &str, value: &str) -> io::Result<()> {
    if value.is_empty() {
        Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{key} must not be empty"),
        ))
    } else {
        Ok(())
    }
}

fn validate_four_ascii(key: &str, value: &str) -> io::Result<()> {
    if value.len() == 4 && value.is_ascii() {
        Ok(())
    } else {
        Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("package.metadata.wrac.{key} must be exactly 4 ASCII bytes"),
        ))
    }
}

fn validate_unique<'a>(key: &str, value: &'a str, seen: &mut HashSet<&'a str>) -> io::Result<()> {
    if seen.insert(value) {
        Ok(())
    } else {
        Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("package.metadata.wrac.plugins.{key} must be unique: {value}"),
        ))
    }
}

/// Compresses everything under `src_dir` into a deflate-compressed zip and writes it to `out_zip`.
fn create_zip(src_dir: &Path, out_zip: &Path) -> io::Result<()> {
    let file = File::create(out_zip)?;
    let mut zip = ZipWriter::new(file);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);

    add_directory_contents(src_dir, src_dir, &mut zip, options)?;
    zip.finish()?;
    Ok(())
}

/// Recursively walks a directory and adds its contents to the zip.
///
/// Entries are sorted by path before processing to make the build deterministic
/// (same inputs always produce the same output).
fn add_directory_contents(
    root: &Path,
    current: &Path,
    zip: &mut ZipWriter<File>,
    options: SimpleFileOptions,
) -> io::Result<()> {
    let mut entries = fs::read_dir(current)?.collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        let relative = path
            .strip_prefix(root)
            .expect("walked path must be inside root");
        // Normalise internal zip paths to the OS-independent `/` separator (Windows fix).
        let zip_path = relative.to_string_lossy().replace('\\', "/");

        if path.is_dir() {
            zip.add_directory(format!("{zip_path}/"), options)?;
            add_directory_contents(root, &path, zip, options)?;
            continue;
        }

        zip.start_file(zip_path, options)?;
        let bytes = fs::read(&path)?;
        zip.write_all(&bytes)?;
    }

    Ok(())
}
