//! Build script that bundles `src-gui/dist` into a single zip and writes it to `OUT_DIR`
//! for release builds.
//!
//! The resulting zip is embedded into the plugin binary via `include_bytes!` in `gui.rs`
//! and served at runtime by the WebView under the `wxp-plugin://` scheme.
//! In debug builds Vite's dev server is used instead, so this script does nothing.

use std::env;
use std::fs::{self, File};
use std::io::{self, Write};
use std::path::{Path, PathBuf};

use serde::Deserialize;
use wrac_gain_parameter_contract::render_typescript_parameter_contract;
use zip::CompressionMethod;
use zip::ZipWriter;
use zip::write::SimpleFileOptions;

fn main() {
    // Tell Cargo to rebuild (regenerate the zip) whenever frontend source files change.
    println!("cargo:rerun-if-changed=../src-gui/index.html");
    println!("cargo:rerun-if-changed=../src-gui/src");
    println!("cargo:rerun-if-changed=../src-gui/package.json");
    println!("cargo:rerun-if-changed=../src-gui/vite.config.ts");
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=../parameter-contract/src/lib.rs");
    println!("cargo:rerun-if-changed=../src-gui/src/generated/parameters.ts");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let manifest_path = manifest_dir.join("Cargo.toml");
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR"));
    // Make [package.metadata.wrac] in Cargo.toml the single source of truth for plugin
    // identity. The plugin descriptor table is generated from it below, while xtask reads
    // the same manifest directly for wrapper and artifact names.
    let metadata = read_wrac_metadata(&manifest_path).expect("failed to read WRAC metadata");
    write_plugin_products(&metadata, &out_dir)
        .expect("failed to write WRAC plugin product metadata");
    check_gui_parameter_contract(&manifest_dir).expect("GUI parameter contract is stale");
    // Skip zip creation for debug builds (the Vite dev server is used instead).
    if env::var("PROFILE").ok().as_deref() != Some("release") {
        return;
    }

    let gui_dist_dir = manifest_dir
        .parent()
        .expect("src-plugin must have a parent directory")
        .join("src-gui")
        .join("dist");
    let out_zip =
        PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("wrac_gain_plugin_gui.zip");

    // Fail early if `npm run build` was not run before the release build.
    if !gui_dist_dir.exists() {
        panic!(
            "frontend build output was not found at {}. Run `npm install && npm run build` in src-gui before release builds.",
            gui_dist_dir.display()
        );
    }

    create_zip(&gui_dist_dir, &out_zip).expect("failed to create frontend zip");
}

fn write_plugin_products(metadata: &WracMetadata, out_dir: &Path) -> io::Result<()> {
    // Rust cannot iterate over Cargo manifest metadata at compile time. Generate the
    // descriptor table once in build.rs so the plugin factory still has a static,
    // allocation-free source for count/descriptor/create queries.
    let mut rust =
        String::from("// Generated by build.rs from package.metadata.wrac. Do not edit by hand.\n");
    rust.push_str(&format!(
        "pub(crate) const COMPANY_NAME: &str = {:?};\n",
        metadata.company_name
    ));
    rust.push_str(&format!(
        "pub(crate) const AUV2_MANUFACTURER_CODE: [u8; 4] = {};\n",
        four_ascii_array_literal(&metadata.auv2_manufacturer_code)
    ));
    rust.push_str("pub(crate) const PLUGIN_DESCRIPTORS: &[PluginDescriptor] = &[\n");
    for plugin in &metadata.plugins {
        rust.push_str("    PluginDescriptor {\n");
        rust.push_str(&format!("        id: {:?},\n", plugin.plugin_id));
        rust.push_str(&format!("        name: {:?},\n", plugin.plugin_name));
        rust.push_str("        vendor: COMPANY_NAME,\n");
        rust.push_str("        url: \"\",\n");
        rust.push_str("        manual_url: \"\",\n");
        rust.push_str("        support_url: \"\",\n");
        rust.push_str("        version: env!(\"CARGO_PKG_VERSION\"),\n");
        rust.push_str("        description: \"Simple gain plugin\",\n");
        rust.push_str("        features: PLUGIN_FEATURES,\n");
        rust.push_str("        auv2: Some(Auv2Descriptor {\n");
        rust.push_str("            manufacturer_code: AUV2_MANUFACTURER_CODE,\n");
        rust.push_str("            manufacturer_name: COMPANY_NAME,\n");
        rust.push_str(&format!(
            "            plugin_type: {},\n",
            four_ascii_array_literal(&plugin.auv2_type)
        ));
        rust.push_str(&format!(
            "            plugin_subtype: {},\n",
            four_ascii_array_literal(&plugin.auv2_subtype)
        ));
        rust.push_str("        }),\n");
        rust.push_str("    },\n");
    }
    rust.push_str("];\n");
    fs::write(out_dir.join("wrac_plugin_products.rs"), rust)
}

fn check_gui_parameter_contract(manifest_dir: &Path) -> io::Result<()> {
    // The checked-in TypeScript file is generated from the same Rust contract crate used
    // by params.rs. build.rs only verifies it, rather than writing into the source tree,
    // so cargo check cannot silently mutate a developer's working copy.
    let generated_path = manifest_dir
        .parent()
        .expect("src-plugin must have a parent directory")
        .join("src-gui")
        .join("src")
        .join("generated")
        .join("parameters.ts");
    let expected = render_typescript_parameter_contract();
    let actual = fs::read_to_string(&generated_path)?;
    if actual == expected {
        Ok(())
    } else {
        Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!(
                "{} is stale. Run `cargo run -p wrac_gain_parameter_contract --bin generate_typescript_parameters`.",
                generated_path.display()
            ),
        ))
    }
}

fn four_ascii_array_literal(value: &str) -> String {
    let bytes = value.as_bytes();
    format!("[{}, {}, {}, {}]", bytes[0], bytes[1], bytes[2], bytes[3])
}

#[derive(Debug, Deserialize)]
struct CargoManifest {
    package: CargoPackage,
}

#[derive(Debug, Deserialize)]
struct CargoPackage {
    metadata: Option<PackageMetadata>,
}

#[derive(Debug, Deserialize)]
struct PackageMetadata {
    wrac: Option<WracMetadata>,
}

#[derive(Debug, Deserialize)]
struct WracMetadata {
    company_name: String,
    auv2_manufacturer_code: String,
    plugins: Vec<WracPluginMetadata>,
}

#[derive(Debug, Deserialize)]
struct WracPluginMetadata {
    plugin_id: String,
    plugin_name: String,
    auv2_type: String,
    auv2_subtype: String,
}

fn read_wrac_metadata(manifest_path: &Path) -> io::Result<WracMetadata> {
    let manifest = fs::read_to_string(manifest_path)?;
    let cargo_manifest: CargoManifest = toml::from_str(&manifest)
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?;
    let metadata = cargo_manifest
        .package
        .metadata
        .ok_or_else(missing_wrac_metadata)?
        .wrac
        .ok_or_else(missing_wrac_metadata)?;
    validate_four_ascii("auv2_manufacturer_code", &metadata.auv2_manufacturer_code)?;
    if metadata.plugins.is_empty() {
        return Err(missing_metadata("plugins"));
    }
    for plugin in &metadata.plugins {
        validate_required("package.metadata.wrac.plugins.plugin_id", &plugin.plugin_id)?;
        validate_required(
            "package.metadata.wrac.plugins.plugin_name",
            &plugin.plugin_name,
        )?;
        validate_four_ascii("auv2_type", &plugin.auv2_type)?;
        validate_four_ascii("auv2_subtype", &plugin.auv2_subtype)?;
    }
    Ok(metadata)
}

fn missing_metadata(key: &str) -> io::Error {
    io::Error::new(
        io::ErrorKind::InvalidData,
        format!("missing package.metadata.wrac.{key} in src-plugin/Cargo.toml"),
    )
}

fn missing_wrac_metadata() -> io::Error {
    io::Error::new(
        io::ErrorKind::InvalidData,
        "missing package.metadata.wrac in src-plugin/Cargo.toml",
    )
}

fn validate_required(key: &str, value: &str) -> io::Result<()> {
    if value.is_empty() {
        Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{key} must not be empty"),
        ))
    } else {
        Ok(())
    }
}

fn validate_four_ascii(key: &str, value: &str) -> io::Result<()> {
    if value.len() == 4 && value.is_ascii() {
        Ok(())
    } else {
        Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("package.metadata.wrac.{key} must be exactly 4 ASCII bytes"),
        ))
    }
}

/// Compresses everything under `src_dir` into a deflate-compressed zip and writes it to `out_zip`.
fn create_zip(src_dir: &Path, out_zip: &Path) -> io::Result<()> {
    let file = File::create(out_zip)?;
    let mut zip = ZipWriter::new(file);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);

    add_directory_contents(src_dir, src_dir, &mut zip, options)?;
    zip.finish()?;
    Ok(())
}

/// Recursively walks a directory and adds its contents to the zip.
///
/// Entries are sorted by path before processing to make the build deterministic
/// (same inputs always produce the same output).
fn add_directory_contents(
    root: &Path,
    current: &Path,
    zip: &mut ZipWriter<File>,
    options: SimpleFileOptions,
) -> io::Result<()> {
    let mut entries = fs::read_dir(current)?.collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        let relative = path
            .strip_prefix(root)
            .expect("walked path must be inside root");
        // Normalise internal zip paths to the OS-independent `/` separator (Windows fix).
        let zip_path = relative.to_string_lossy().replace('\\', "/");

        if path.is_dir() {
            zip.add_directory(format!("{zip_path}/"), options)?;
            add_directory_contents(root, &path, zip, options)?;
            continue;
        }

        zip.start_file(zip_path, options)?;
        let bytes = fs::read(&path)?;
        zip.write_all(&bytes)?;
    }

    Ok(())
}
