//! Build-script helpers for WRAC plugin crates.
//!
//! Product crates call this crate from `build.rs` to turn `wrac-plugin.toml`
//! into generated Rust descriptors and, for release builds, to package the
//! frontend `dist` directory into an embedded bundle. Runtime plugin code should
//! not depend on this crate.

use std::{
    env,
    fs::{self, File},
    io::{self, Write},
    path::{Path, PathBuf},
};

use zip::{CompressionMethod, ZipWriter, write::SimpleFileOptions};

pub struct PluginDescriptorCodegenConfig {
    pub manifest_path: Option<PathBuf>,
    pub output_file_name: String,
}

impl Default for PluginDescriptorCodegenConfig {
    fn default() -> Self {
        Self {
            manifest_path: None,
            output_file_name: "wrac_plugin_products.rs".to_string(),
        }
    }
}

pub struct FrontendBundleConfig<'a> {
    pub dist_dir: PathBuf,
    pub output_file_name: &'a str,
    pub rerun_if_changed: &'a [&'a str],
    pub missing_dist_build_command: &'a str,
}

pub fn generate_plugin_descriptors(config: PluginDescriptorCodegenConfig) -> io::Result<PathBuf> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").map_err(|error| {
        io::Error::new(
            io::ErrorKind::NotFound,
            format!("CARGO_MANIFEST_DIR is not available: {error}"),
        )
    })?);
    let manifest_path = config
        .manifest_path
        .unwrap_or_else(|| manifest_dir.join("wrac-plugin.toml"));
    println!("cargo:rerun-if-changed={}", manifest_path.display());
    let metadata =
        wrac_manifest::read_dedicated_manifest(&manifest_path).map_err(to_invalid_data)?;
    let out_dir = PathBuf::from(env::var("OUT_DIR").map_err(|error| {
        io::Error::new(
            io::ErrorKind::NotFound,
            format!("OUT_DIR is not available: {error}"),
        )
    })?);
    let output = out_dir.join(config.output_file_name);
    write_plugin_products(&metadata, &output)?;
    Ok(output)
}

pub fn build_frontend_bundle(config: FrontendBundleConfig<'_>) -> io::Result<Option<PathBuf>> {
    for path in config.rerun_if_changed {
        println!("cargo:rerun-if-changed={path}");
    }

    if env::var("PROFILE").ok().as_deref() != Some("release") {
        return Ok(None);
    }

    if !config.dist_dir.exists() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!(
                "frontend build output was not found at {}. {}",
                config.dist_dir.display(),
                config.missing_dist_build_command
            ),
        ));
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").map_err(|error| {
        io::Error::new(
            io::ErrorKind::NotFound,
            format!("OUT_DIR is not available: {error}"),
        )
    })?);
    let output_path = out_dir.join(config.output_file_name);
    create_zip(&config.dist_dir, &output_path)?;
    Ok(Some(output_path))
}

fn write_plugin_products(
    metadata: &wrac_manifest::PluginManifest,
    output: &Path,
) -> io::Result<()> {
    let mut rust =
        String::from("// Generated by wrac_build from wrac-plugin.toml. Do not edit by hand.\n");
    rust.push_str(&format!(
        "pub(crate) const COMPANY_NAME: &str = {:?};\n",
        metadata.company_name
    ));
    rust.push_str(&format!(
        "pub(crate) const AUV2_MANUFACTURER_CODE: [u8; 4] = {};\n",
        four_ascii_array_literal(&metadata.auv2_manufacturer_code)?
    ));
    if let Some(aax_manufacturer_id) = metadata.aax_manufacturer_id.as_ref() {
        rust.push_str(&format!(
            "pub(crate) const AAX_MANUFACTURER_ID: u32 = {};\n",
            fourcc_literal(aax_manufacturer_id)?
        ));
    }
    rust.push_str(&format!(
        "pub(crate) const AAX_PACKAGE_VERSION: u32 = {};\n",
        aax_package_version_literal()?
    ));
    for (index, plugin) in metadata.plugins.iter().enumerate() {
        rust.push_str(&format!(
            "const PLUGIN_{index}_FEATURES: &[PluginFeature] = &{};\n",
            plugin_feature_array_literal(&plugin.clap_features)?
        ));
        write_aax_stem_config_statics(&mut rust, index, plugin)?;
        rust.push_str(&format!(
            "unsafe extern \"C\" fn plugin_{index}_aax_get_num_stem_configs() -> u32 {{\n"
        ));
        rust.push_str(&format!(
            "    PLUGIN_{index}_AAX_STEM_CONFIGS.len() as u32\n"
        ));
        rust.push_str("}\n");
        rust.push_str(&format!(
            "unsafe extern \"C\" fn plugin_{index}_aax_get_stem_config(index: u32) -> *const AaxStemConfig {{\n"
        ));
        rust.push_str(&format!(
            "    PLUGIN_{index}_AAX_STEM_CONFIGS.get(index as usize).map_or(core::ptr::null(), |config| config)\n"
        ));
        rust.push_str("}\n");
    }
    rust.push_str("pub(crate) const PLUGIN_DESCRIPTORS: &[PluginDescriptor] = &[\n");
    for (index, plugin) in metadata.plugins.iter().enumerate() {
        rust.push_str("    PluginDescriptor {\n");
        rust.push_str(&format!("        id: {:?},\n", plugin.plugin_id));
        rust.push_str(&format!("        name: {:?},\n", plugin.plugin_name));
        rust.push_str("        vendor: COMPANY_NAME,\n");
        rust.push_str(&format!("        url: {:?},\n", metadata.homepage_url));
        rust.push_str(&format!("        manual_url: {:?},\n", metadata.manual_url));
        rust.push_str(&format!(
            "        support_url: {:?},\n",
            metadata.support_url
        ));
        rust.push_str("        version: env!(\"CARGO_PKG_VERSION\"),\n");
        rust.push_str(&format!(
            "        description: {:?},\n",
            metadata.description
        ));
        rust.push_str(&format!("        features: PLUGIN_{index}_FEATURES,\n"));
        rust.push_str("        auv2: Some(Auv2Descriptor {\n");
        rust.push_str("            manufacturer_code: AUV2_MANUFACTURER_CODE,\n");
        rust.push_str("            manufacturer_name: COMPANY_NAME,\n");
        rust.push_str(&format!(
            "            plugin_type: {},\n",
            four_ascii_array_literal(&plugin.auv2_type)?
        ));
        rust.push_str(&format!(
            "            plugin_subtype: {},\n",
            four_ascii_array_literal(&plugin.auv2_subtype)?
        ));
        rust.push_str("        }),\n");
        rust.push_str("        vst3: Some(Vst3Descriptor {\n");
        rust.push_str(&format!(
            "            subcategories: {:?},\n",
            plugin.vst3_subcategories
        ));
        rust.push_str(&format!(
            "            component_id: {:?},\n",
            wrac_manifest::vst3_component_id_bytes(&plugin.vst3_component_id)
                .map_err(to_invalid_data)?
        ));
        rust.push_str("        }),\n");
        if plugin.aax_categories.is_some() {
            rust.push_str("        aax: Some(AaxDescriptor {\n");
            rust.push_str(&format!(
                "            package_name: {:?},\n",
                metadata.bundle_name
            ));
            rust.push_str("            package_version: AAX_PACKAGE_VERSION,\n");
            rust.push_str(&format!(
                "            categories: {},\n",
                aax_categories_literal(plugin.aax_categories.as_deref().unwrap_or_default())?
            ));
            rust.push_str("            manufacturer_id: AAX_MANUFACTURER_ID,\n");
            rust.push_str(&format!(
                "            product_id: {},\n",
                fourcc_literal(
                    plugin
                        .aax_product_id
                        .as_deref()
                        .ok_or_else(|| io::Error::new(
                            io::ErrorKind::InvalidData,
                            "missing AAX product ID"
                        ))?
                )?
            ));
            rust.push_str(&format!(
                "            get_num_stem_configs: plugin_{index}_aax_get_num_stem_configs,\n"
            ));
            rust.push_str(&format!(
                "            get_stem_config: plugin_{index}_aax_get_stem_config,\n"
            ));
            rust.push_str("        }),\n");
        } else {
            rust.push_str("        aax: None,\n");
        }
        rust.push_str("    },\n");
    }
    rust.push_str("];\n");
    fs::write(output, rust)
}

fn four_ascii_array_literal(value: &str) -> io::Result<String> {
    let bytes = wrac_manifest::four_ascii_bytes(value).map_err(to_invalid_data)?;
    Ok(format!(
        "[{}, {}, {}, {}]",
        bytes[0], bytes[1], bytes[2], bytes[3]
    ))
}

fn fourcc_literal(value: &str) -> io::Result<String> {
    Ok(format!(
        "0x{:08X}",
        wrac_manifest::fourcc(value).map_err(to_invalid_data)?
    ))
}

fn plugin_feature_array_literal(features: &[String]) -> io::Result<String> {
    let items = features
        .iter()
        .map(|feature| {
            wrac_manifest::clap_feature_variant(feature)
                .map(|variant| format!("PluginFeature::{variant}"))
                .ok_or_else(|| {
                    io::Error::new(
                        io::ErrorKind::InvalidData,
                        format!("unsupported CLAP feature value: {feature}"),
                    )
                })
        })
        .collect::<io::Result<Vec<_>>>()?;
    Ok(format!("[{}]", items.join(", ")))
}

fn aax_categories_literal(categories: &[String]) -> io::Result<String> {
    let values = categories
        .iter()
        .map(|category| {
            wrac_manifest::aax_category_bits(category)
                .map(|value| format!("0x{value:08X}"))
                .map_err(to_invalid_data)
        })
        .collect::<io::Result<Vec<_>>>()?;
    Ok(values.join(" | "))
}

fn write_aax_stem_config_statics(
    rust: &mut String,
    plugin_index: usize,
    plugin: &wrac_manifest::PluginProduct,
) -> io::Result<()> {
    let mut items = Vec::new();
    for (stem_index, stem_config) in plugin.aax_stem_configs.iter().enumerate() {
        rust.push_str(&format!(
            "static PLUGIN_{plugin_index}_AAX_STEM_{stem_index}_NAME: &[u8] = &{:?};\n",
            nul_terminated(&stem_config.name)
        ));
        items.push(format!(
            "AaxStemConfig {{ name: PLUGIN_{plugin_index}_AAX_STEM_{stem_index}_NAME.as_ptr().cast(), format_in: {}, format_out: {}, plugin_id: {} }}",
            wrac_manifest::aax_stem_format_value(&stem_config.input).map_err(to_invalid_data)?,
            wrac_manifest::aax_stem_format_value(&stem_config.output).map_err(to_invalid_data)?,
            fourcc_literal(&stem_config.plugin_id)?
        ));
    }
    rust.push_str(&format!(
        "static PLUGIN_{plugin_index}_AAX_STEM_CONFIGS: &[AaxStemConfig] = &[{}];\n",
        items.join(", ")
    ));
    Ok(())
}

fn nul_terminated(value: &str) -> Vec<u8> {
    let mut bytes = value.as_bytes().to_vec();
    bytes.push(0);
    bytes
}

fn aax_package_version_literal() -> io::Result<String> {
    let major = aax_version_component("CARGO_PKG_VERSION_MAJOR")?;
    let minor = aax_version_component("CARGO_PKG_VERSION_MINOR")?;
    let patch = aax_version_component("CARGO_PKG_VERSION_PATCH")?;
    Ok(format!("0x{major:02X}{minor:02X}{patch:02X}00"))
}

fn aax_version_component(name: &str) -> io::Result<u32> {
    let value = env::var(name)
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?
        .parse::<u32>()
        .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error))?;
    if value > 0xFF {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            format!("{name} must fit in one byte for AAX package_version: {value}"),
        ));
    }
    Ok(value)
}

fn to_invalid_data(error: Box<dyn std::error::Error>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, error.to_string())
}

fn create_zip(src_dir: &Path, out_zip: &Path) -> io::Result<()> {
    let file = File::create(out_zip)?;
    let mut zip = ZipWriter::new(file);
    let options = SimpleFileOptions::default().compression_method(CompressionMethod::Deflated);

    add_directory_contents(src_dir, src_dir, &mut zip, options)?;
    zip.finish()?;
    Ok(())
}

fn add_directory_contents(
    root: &Path,
    current: &Path,
    zip: &mut ZipWriter<File>,
    options: SimpleFileOptions,
) -> io::Result<()> {
    let mut entries = fs::read_dir(current)?.collect::<Result<Vec<_>, _>>()?;
    entries.sort_by_key(|entry| entry.path());

    for entry in entries {
        let path = entry.path();
        let relative = path
            .strip_prefix(root)
            .expect("walked path must be inside root");
        let zip_path = relative.to_string_lossy().replace('\\', "/");

        if path.is_dir() {
            zip.add_directory(format!("{zip_path}/"), options)?;
            add_directory_contents(root, &path, zip, options)?;
            continue;
        }

        zip.start_file(zip_path, options)?;
        let bytes = fs::read(&path)?;
        zip.write_all(&bytes)?;
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use std::{
        fs,
        path::PathBuf,
        sync::Mutex,
        time::{SystemTime, UNIX_EPOCH},
    };

    static ENV_LOCK: Mutex<()> = Mutex::new(());

    #[test]
    fn plugin_descriptor_codegen_preserves_host_visible_ids() {
        let _env_lock = ENV_LOCK.lock().expect("env lock must not be poisoned");
        let temp_dir = unique_temp_dir();
        fs::create_dir_all(&temp_dir).unwrap();
        let manifest_path = temp_dir.join("wrac-plugin.toml");
        let output_path = temp_dir.join("wrac_plugin_products.rs");
        fs::write(&manifest_path, FIXTURE_MANIFEST).unwrap();

        unsafe {
            std::env::set_var("CARGO_PKG_VERSION_MAJOR", "1");
            std::env::set_var("CARGO_PKG_VERSION_MINOR", "2");
            std::env::set_var("CARGO_PKG_VERSION_PATCH", "3");
        }

        let manifest = wrac_manifest::read_dedicated_manifest(&manifest_path).unwrap();
        super::write_plugin_products(&manifest, &output_path).unwrap();
        let generated = fs::read_to_string(&output_path).unwrap();

        assert!(
            generated
                .contains("pub(crate) const AUV2_MANUFACTURER_CODE: [u8; 4] = [89, 114, 67, 111];")
        );
        assert!(generated.contains("pub(crate) const AAX_MANUFACTURER_ID: u32 = 0x5972436F;"));
        assert!(generated.contains("pub(crate) const AAX_PACKAGE_VERSION: u32 = 0x01020300;"));
        assert!(generated.contains("component_id: [202, 17, 32, 130, 236, 55, 239, 92, 146, 215, 236, 126, 103, 32, 113, 149],"));
        assert!(generated.contains("product_id: 0x5774476E,"));
        assert!(generated.contains("plugin_id: 0x5774474D"));
        assert!(generated.contains("plugin_id: 0x57744753"));

        fs::remove_dir_all(temp_dir).unwrap();
    }

    fn unique_temp_dir() -> PathBuf {
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!("wrac-build-test-{}-{nanos}", std::process::id()))
    }

    const FIXTURE_MANIFEST: &str = r#"
schema_version = 1

[package]
version_source = "cargo"

[bundle]
company_name = "Your Company"
auv2_manufacturer_code = "YrCo"
aax_manufacturer_id = "YrCo"
bundle_name = "WRAC Gain"
bundle_identifier = "com.your-company.wrac-gain"
homepage_url = "https://example.com/wrac-gain"
manual_url = "https://example.com/wrac-gain/manual"
support_url = "https://example.com/support"
description = "Simple gain plugin"
copyright = "Copyright 2026 Your Company"
supported_formats = ["clap", "vst3", "au", "aax"]

[[plugins]]
plugin_id = "com.your-company.wrac-gain"
plugin_name = "WRAC Gain"
clap_features = ["audio-effect", "utility", "stereo"]
vst3_subcategories = "Fx|Tools"
vst3_component_id = "822011ca-37ec-5cef-92d7-ec7e67207195"
standalone_name = "WRAC Gain Standalone"
auv2_type = "aufx"
auv2_subtype = "WtGn"
aax_categories = ["effect"]
aax_product_id = "WtGn"

[[plugins.aax_stem_configs]]
name = "Mono"
input = "mono"
output = "mono"
plugin_id = "WtGM"

[[plugins.aax_stem_configs]]
name = "Stereo"
input = "stereo"
output = "stereo"
plugin_id = "WtGS"
"#;
}
